INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AMERICAN', 'American Airlines', 4, 227);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ASIANA', 'Asiana Airlines', 2, 118);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ADRIA', 'Adria Airways', 4, 196);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('EUROPA', 'Air Europa', 2, 66);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AEGEAN', 'Aegean Airlines', 8, 87);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AEROFLOT', 'Aeroflot Russian Airlines', 4, 187);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIRFRANS', 'Air France', 4, 73);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR BERLIN', 'Air Berlin', 89, 55);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIRINDIA', 'Air India Limited', 4, 102);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR MALTA', 'Air Malta', 4, 149);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR SICILIA', 'Air Sicilia', 2, 106);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ALL NIPPON', 'All Nippon Airways', 2, 110);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR CANADA', 'Air Canada', 7, 36);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIRBALTIC', 'Air Baltic', 4, 131);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AUSTRIAN', 'Austrian Airlines', 4, 11);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ALITALIA', 'Alitalia', 2, 106);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR CHINA', 'Air China', 6, 46);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('DOLOMOTI', 'Air Dolomiti', 8, 106);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SHAMROCK', 'Aer Lingus', 4, 99);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SPEEDBIRD', 'British Airways', 4, 75);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('BEE-LINE', 'Brussels Airlines', 2, 19);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('CONDOR', 'Condor Flugdienst', 38, 55);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('CROATIA', 'Croatia Airlines', 8, 95);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('CYPRUS', 'Cyprus Airways', 3, 53);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('DELTA', 'Delta Air Lines', 2, 227);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('EGYPTAIR', 'Egyptair', 2, 63);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ELAL', 'El Al Israel Airlines', 3, 100);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('EMIRATES', 'Emirates', 2, 2);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ETHIOPIAN', 'Ethiopian Airlines', 2, 67);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ETIHAD', 'Etihad Airways', 2, 2);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('EASY', 'easyJet', 8, 75);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('FINNAIR', 'Finnair', 4, 68);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('FORMOSA', 'Formosa Airlines', 4, 223);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('GERMANIA', 'Germania', 4, 55);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('GERMAN WINGS', 'Germanwings', 2, 55);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('HAINAN', 'Hainan Airlines', 2, 46);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('YELLOW CAB', 'TUIfly', 29, 55);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('IBERIA', 'Iberia Airlines', 6, 66);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ICEAIR', 'Icelandair', 2, 105);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('INTERSKY', 'Intersky', 2, 11);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('KLM', 'KLM Royal Dutch Airlines', 4, 162);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('POLLOT', 'LOT Polish Airlines', 10, 175);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('LUFTHANSA', 'Lufthansa', 258, 55);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('LUXAIR', 'Luxair', 2, 130);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('MERAIR', 'Meridiana', 10, 106);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('FLYNIKI', 'Niki', 2, 11);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('NOR SHUTTLE', 'Norwegian Air Shuttle', 12, 163);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('NOUVELAIR', 'Nouvel Air Tunisie', 4, 218);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('OMAN AIR', 'Oman Air', 2, 168);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SUNTURK', 'Pegasus Airlines', 2, 220);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('QANTAS', 'Qantas', 2, 12);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('QATARI', 'Qatar Airways', 2, 183);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('ROYALAIR MAROC', 'Royal Air Maroc', 4, 133);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('JORDANIAN', 'Royal Jordanian', 4, 109);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR AZORES', 'SATA International', 2, 180);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SPRINGBOK', 'South African Airways', 4, 242);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SCANDINAVIAN', 'Scandinavian Airlines System', 15, 193);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SIBERIAN AIRLINES', 'S7 Airlines', 4, 187);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SINGAPORE', 'Singapore Airlines', 4, 194);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SWISS', 'Swiss International Air Lines', 6, 41);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SUNEXPRESS', 'SunExpress', 4, 220);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('TAM', 'TAM Brazilian Airlines', 2, 30);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('AIR PORTUGAL', 'TAP Portugal', 4, 180);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('TUNAIR', 'Tunisair', 6, 218);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('THAI', 'Thai Airways International', 2, 214);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('TURKAIR', 'Turkish Airlines', 4, 220);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('TAROM', 'Tarom', 4, 185);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('UNITED', 'United Airlines', 16, 227);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SVERDLOVSK AIR', 'Ural Airlines', 4, 187);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('U S AIR', 'US Airways', 14, 227);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('UKRAINE INTERNATIONAL', 'Ukraine International Airlines', 2, 225);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('VIRGIN', 'Virgin Atlantic Airways', 8, 75);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('VELOCITY', 'Virgin Australia', 0, 12);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('POLET', 'Polet Airlines (Priv)', 2, 187);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('SKYFOX', 'SkyWork Airlines', 2, 41);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('LITUANICA', 'Air Lituanica', 2, 129);
INSERT INTO Airline(Callsign, Name, SlotCount, Country) VALUES ('VOLOTEA', 'VOLOTEA Airways', 4, 66);
