INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Qxuh55EZ', 'Moving', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rhOGZsoN', 'Moving', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('FvvCKgV1', 'Moving', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ZwfhYarq', 'Moving', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QK1qM5fW', 'Moving', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Lag8aowa', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pq13hsz8', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Nv48lcjq', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('mk9KPkzC', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pRV51KHy', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dBV2rOK8', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UDO9sNPp', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TqQNCNNm', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DC0oKMqA', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jHw2psqy', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('cm95g4Dc', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3u19Ww0d', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('p7gjA3wn', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MuXHSHiw', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Az06PP4o', 'Parking', 'tanker');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jykTAura', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('j9ORq82K', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9S3kRkiL', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9fHzxduq', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fclIXrf0', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aKVseamt', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4HATwDDQ', 'Moving', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Gws3IHTE', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rMmlHm8U', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zGyF16QR', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('uxKg6N0q', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2kr77UkO', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zrUsYmR7', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WeV32IvF', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qi7wGKgO', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MTX5ukbl', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('cTmvKQ25', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WecifiXZ', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('oNQV7bRW', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JpGWBvVf', 'Parking', 'apron stairs');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Dz99waHH', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iX0qCz47', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Aw73BNis', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yF1FaOQA', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WXlSh48d', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bMbAt6qa', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('a0RixR8n', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qF3RGhVR', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('FHhWYUbX', 'Moving', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AzAiAkP8', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wL7tQrAU', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Z7lDo9Ni', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AbCvHOSP', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UUdbCeod', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('hDUXBRAA', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('8JJ5RVaO', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('E8AEYk7c', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('uuOzdg49', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4Mi8QGi7', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('CvOaS9rm', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WCxjuwST', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('apyZzzEL', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MpsyB6I9', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('K5J3RWqU', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jd0y5LbC', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JOPzgVMT', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3ERbm30N', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0iqPQimS', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pAvGwHhW', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ka3dcW5H', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('i5g2MU1P', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('a0HsDXxi', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Tn5EcfTr', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WJwHjnBT', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('d7Hfou53', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ct3bOgTY', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1ZB9O48H', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('GmLFM5U2', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5bfLMTal', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('KzSUUkvH', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fHOkh4cF', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('c6LXRuYc', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('c67SsFgq', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('IpcnKsEn', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('D0V4HaPh', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sL0cTI1P', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WmuQZcGg', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WNo54Aw3', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ES7Gu46w', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LvtQqYQR', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7v8etxjh', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('X0vDA4Hm', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MAb7Vo41', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gOjHKWPP', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7ijzIbVc', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ct6QQBnH', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Wcg2UUVo', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XaIRfLL9', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lXCvRckJ', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bTlQBDBW', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AcObFyIc', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('xYrsXJTh', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pnuiAOEL', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dKRVeXzg', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jzg5XAkY', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LsJkhAxJ', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aOr68COU', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5M0nmVHV', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pDGJSl4X', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6eGzBntj', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('uCcWpMLA', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('PrUf1SKR', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JjCMZJMl', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('GWYpq9DO', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RifxmE9M', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sutSnGz0', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DfB2d0dO', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ZpefpQmq', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rJofmvtH', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Eii2VgpJ', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('G0i5OEpP', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('e5TvrIUj', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wixwzhxI', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('uQQHMR5w', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('xZI4Qcen', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zZCMMGC8', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('GI3kpqon', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('W9dZWZeD', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('KC0e2zPj', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ok4qVXox', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QMAkzWbn', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('n3TDkyfQ', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('kiQxyPft', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jh652BOx', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HVEhgdTx', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AFIUAODr', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('USGU7P1l', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UKp07mgG', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('d8YSL9OA', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RTQ4btMd', 'Parking', 'luggage cart');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('mUBIMaVK', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('n84gbdW2', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pWXYpwdf', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fsvw6afN', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ztdqDHAZ', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('PgK0ThJW', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3gyOZNN1', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UIf2s0a8', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('mvPEsby1', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Qm6AB7IU', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7gtAOGPN', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zPCV2qi6', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('EMoOxhKD', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dqe1uTTg', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('p7vspMnB', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9VSfuzwY', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('KofzACT9', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('8qNPXFdw', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('EU5zoliN', 'Moving', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('BAEZY4eU', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9WlEskok', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1F56yTZB', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2Q9FxPbn', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ijDZuwj7', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UtG99ZJO', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fm6I8fLF', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('A1GMHs1p', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('g817EhOp', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pqlj3l8R', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7hWCJ2hB', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LM22KhFU', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ti0u06OP', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gWInWJwx', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('S6hc7Kxo', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ghnzmmuj', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fEGLQce4', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bweNSZj7', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DkdmSlxb', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QF4zQ90E', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vjdrgucV', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('giZsSYKv', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MR4krpDX', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('IgDZXFfV', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RrhsWKFo', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vQCvEubR', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XuW7I07l', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Y06AYF1o', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LaIcrd8l', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9Uq7Gb7w', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('elhWwTGn', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pGS64bGc', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6oSjMAsv', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('IjoovksG', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QP8ZRfPO', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('OLybmkqE', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pUX8Hmr8', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aJZsn3O9', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yrcifJpH', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Pl6pMunk', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dPXJRthZ', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('FcWA1TNG', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QZrzoIp9', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aWx80qwo', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('L8oc71FW', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('YSE524Lo', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LzlxlEs4', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JBTPTL4y', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('X8KOrcsJ', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('r5wSXmFA', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6XIOV7BL', 'Parking', 'pushback');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vD0bKvHF', 'Moving', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('SXeByXN3', 'Moving', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('S5dVmUZq', 'Moving', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Y9Kkjh2t', 'Moving', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('tq0qvKvw', 'Parking', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0tpaRlNI', 'Parking', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('W02h375p', 'Parking', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('c88YJjuI', 'Parking', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JDypxGlr', 'Parking', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Mft72MmG', 'Parking', 'follow me');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('D530d9dW', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qhXen4GQ', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('e7bJSpIK', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('FmX4ogrz', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bCTSLJFa', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6iMjyrCD', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('G8KiXFvp', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qKKy1dNB', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('l5dZTKln', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HvN8RnNM', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UXHIz8Vg', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('i5sNACwN', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4NASAIN5', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('B35jnyfS', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NNEIOv6z', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('tLYUQmeN', 'Moving', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('09S37kJ9', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('N7BPPqIQ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('SbseDaT0', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('x4aPXbjz', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ePlYPjvB', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('FUWym8J2', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('eKwghgVr', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('OIopmlOR', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bSg1S3HA', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HH3NiI08', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dQphBaAc', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('8aYh6TEJ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qVabg678', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ZF81IVo7', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('g7YckYwM', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('cgEUK66i', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('KuLYOKqL', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('FwfriWYP', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pxSnn463', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XvuA5Zj9', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DHcz8lhc', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dP4nXyUH', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('edvq0nfC', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MwkthWGO', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1psRa7Yh', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7hjialhR', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('M8kYIl2f', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('82OFMi6a', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dKJw3hwP', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('oW7WV2PX', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fdPLAJGJ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zM3PwpGW', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('VkgyofKd', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wgAsc9y6', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HsqSMz47', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('q5Eq2lkI', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Hk6M6HI7', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zCbYV72v', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('hvleTDwu', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('oSkHi62W', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0RvsVSqW', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('y4lLMxcZ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0yzLWgWE', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ldx8eiAS', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dCOxDiUZ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('05VOsnzm', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5Mhgfbhm', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Tw3flSDh', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('oUgiUH3n', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('N5lEP2l3', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wAbRCvxA', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ok5NJPhR', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WeRBEoQX', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('PaM3gQc6', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('90Qd60O0', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5bIGJKSI', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XFWsBQ8X', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('o8YVRm9x', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6Cgd2Sa3', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iJiTtP8S', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('oeKLTvTp', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Iya3vR89', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AQMU6s9i', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('VHe2QM9G', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1iVrLN7X', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('YSuOkqW2', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NIwfjN4v', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('brBSPOnB', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gzwCkn5z', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('EY4suKqh', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XX4P4beU', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lTQenTrz', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('W6nxtai2', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('c306PCMZ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qZEAKKwu', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('VSWgdr4m', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jjS61QD8', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('YWxOlT8l', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('32TcqfvX', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('avP0E7ny', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NJKItJlr', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XLyeHUKd', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('xi2wz1ao', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5HW0Xhp9', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('U1yZrZMV', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('s8FEgnA0', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('BwAHTpZ6', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iiuBekWW', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MTW6sNUK', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('z21ca8HD', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UtqlpFZ9', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UOfCMvnj', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('YsID5G3f', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NcwhMPSc', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('g3uox7FM', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('v1SYv97U', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('O6m0lg3Q', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('a93TOSZC', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iguLiE36', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dAx1iRBe', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('PTPmEhqR', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ksXTprII', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('V9ZrjCWP', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('8gfburl2', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bZlokfYJ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('U0q0omBf', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('I5ivIUGy', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('8i1MqNpL', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('xDF7XvON', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3JNbi0N2', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RqMQOKAj', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('eV43jNoX', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DOmPV4Gk', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AKffx2MU', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DpA4ETb7', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wL4cNYFY', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3crYXJCO', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('okM75t8H', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3Pfpr3jk', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6H71b3Iy', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('EE3B5SwF', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HFOXaDmc', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2q111jsi', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TLqxKZk5', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('tG55W5PJ', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('U9tmOXu2', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zN5HVnXf', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dxmGN30G', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('kETPFALf', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yOVJQ9Nk', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ukNaPNrf', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LrnSyfki', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RqYYysDe', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dnoqcmoh', 'Parking', 'luggage loader');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sTrwOrRi', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ZBRVt2mX', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Db9GbhMu', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('hjepTqO4', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('27XXsmkM', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Rg1DBRg0', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HBaZLckw', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5UDqHzdC', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2SRLzGEH', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3SDabxOw', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sco5t0Zc', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WxvFlANz', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('q74B3loP', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gdCbIZM7', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0KCLisaK', 'Moving', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2Jjg0tXJ', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('geVX7btA', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NToZVWq2', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DL6N0U1n', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('catZq5yR', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TyNk9YIr', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('GhwDyX2G', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0CnX5e5y', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dv9riiwV', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HAgo53kw', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('YayPFdmt', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0FiK3ANQ', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ufu5ycHC', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4xontPMI', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jFzs4sgv', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('E2beUHtW', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('SFHJBtNH', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JQst5GJ3', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0Kv1aTXu', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LPCLZ3Hk', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('E7SoUQRO', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('T3q9UZqL', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('CATxQcPm', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('KkOQh2TH', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('EW1902IV', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2JMrgA2D', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wrITME5T', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('64w7NuFX', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fINiCXPW', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('40jY2Qa7', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TVbm0C8d', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2mCM9IDD', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zdYy076L', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('CsvnJFfu', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('55OByHLU', 'Parking', 'cleaning vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rVDeaYE1', 'Moving', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dCF81ze3', 'Moving', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lFATgWEf', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yltFDdP0', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('t76qoeCM', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WOhWdWq2', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Q0u45Ddy', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('O68pNj4y', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Rr1afegx', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('uV2JQVwW', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('SNhHTT83', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('B8HwKv8T', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LxcAztvP', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('tkpOGu3c', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rYdbOsmq', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RXBVFzlw', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iwX1D6Gz', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0PBtlEiN', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('F4OdumAP', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('69bIaBAw', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MbnNRDUS', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Rc2LDsCw', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NcMohzi2', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fsGwzuFm', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('SHaqKH82', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NwIIQGH4', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DxJaMpug', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1b3EhKXM', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ABW4QCSc', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('I3mCfHGh', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lQazektD', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pP5KDyN7', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vXbpecVx', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JvNYoR5L', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('k7SeTeI9', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vUwtwLhE', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yNUjia50', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('PZqMS0YF', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gzAXnzBr', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('emYE5QOE', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QHyfRhU8', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rPCZsI6x', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('oOYYSzHN', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0t1zsDmz', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RFPQ2V0h', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('B0tNwByB', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ji8kWMdq', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4987SaKj', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('irkNZvJT', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('m4VmmAVB', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9DVPwVqx', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('reUAV3tT', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('S6nAwg6f', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NhSAwBn4', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vtiU2xEb', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('3QuiTj5p', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qft1dWc5', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('E6YaOamK', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lzOBLZkZ', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Ua6t5WTw', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gHnmJKzg', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('xjTQIDrJ', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aVZhw3y5', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ZjYQbkBo', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('pSiJZIQQ', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UDvftpZv', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('kka071fu', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('n0vZVQqv', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ep1CgQu8', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('XSKIjfCN', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vc9Si55Y', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1vYjcJf0', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yTkPTsvm', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DLhC5h6H', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WRMO33DU', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('G5PakOT8', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zuuol4DS', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9J6rgATc', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('A7PbCAXM', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jgzpngcF', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ZX2ahjXZ', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('UoQV1k37', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6QI6pbUn', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('5AAYI7Ms', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RXdVVdxO', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wGNJUpqi', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('k5bfAYsH', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('qsIXdiNE', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7rQiv7Ft', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TxWDdTJh', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('mAN3kvmv', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iwfzfb9B', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('6UfJox6T', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TI9JwjeB', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zESnyxfp', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1UgOJuHq', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zs3tidgo', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7owWigO8', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('CUx19NmU', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4h4zyaVF', 'Parking', 'toilet vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Tywj8t4p', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('RslBxQhx', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('7HlzwK3W', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9Znkk45U', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('mVdU9i8D', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ewAO1hc3', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vEaUe7P5', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lsWqQljv', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0gz8YWkI', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yQTqyNa4', 'Moving', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wCrsHb42', 'Parking', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('L2zsdkt1', 'Parking', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('yS5ma1Vr', 'Parking', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('EgQQKykm', 'Parking', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9mhnA8US', 'Parking', 'construction vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('k1szk3sp', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('kAo9BF84', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('z7lVE7sl', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('GjveT8j5', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('JcbhvAkR', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('2LM5oj5l', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('j7j3Ntit', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('TqRwN5Z1', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('wsAzMjP8', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('1rLMpwW7', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('zTJ3MjsC', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('gJDSzOln', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('rLaHgm85', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('ct0aL1tk', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('0DiZaHWt', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('a5Y3u68T', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('vxVvcCVD', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('O8Wb0IH6', 'Moving', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NAXaV4Yx', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('9eVnWYtj', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LOJFhgmC', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aZy6LeFh', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('tToHO5hT', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('u9GrEmd6', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sjCMuRCu', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('WGC1KLSn', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('DtCoLuZK', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('PkG0eMqi', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('kY9vdIBi', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('LUJY1Mru', 'Parking', 'passenger bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('fJt3rJpe', 'Moving', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('QtQs4ca5', 'Moving', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('CPYdfybF', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('dSZeKVti', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('bstRrVbt', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4Tri7wkO', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iCQopEPp', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('4FJWBkm5', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HL9DkmDp', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('opalZ9Tj', 'Parking', 'crew bus');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('AKRlGjo3', 'Moving', 'emergency vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Bhsjmg4w', 'Moving', 'emergency vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('aniMOX54', 'Parking', 'emergency vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('MZBQ0EMN', 'Parking', 'emergency vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('laqFF62o', 'Parking', 'emergency vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('H0Gpmqzv', 'Parking', 'emergency vehicle');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('CNzguXDN', 'Moving', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sDBGgNk4', 'Moving', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('itP18ofD', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('sjab2ZGo', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('e6PbkTMj', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('orvZgdHF', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('GpTLEcvs', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('lqE9npn3', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('I5NXTdnN', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('30EwZCLi', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('znlWxU7y', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('81PSMdwj', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('iuGKCXgO', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('NlnvykLx', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('kuZJ2dlX', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('VcB8rDfJ', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('jjSG5UMI', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('uslRawkX', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('HTXY6xDU', 'Parking', 'fire truck');
INSERT INTO ApronVehicle(LicensePlate, Status, Job) VALUES ('Z9h8rH2j', 'Parking', 'fire truck');
