INSERT INTO PlaneType(Name) VALUES ('Aerospatiale (Sud Aviation) Se.210 Caravelle');
INSERT INTO PlaneType(Name) VALUES ('Aerospatiale SN.601 Corvette');
INSERT INTO PlaneType(Name) VALUES ('Aerospatiale/Alenia ATR 42-300');
INSERT INTO PlaneType(Name) VALUES ('Aerospatiale/Alenia ATR 42-500');
INSERT INTO PlaneType(Name) VALUES ('Aerospatiale/Alenia ATR 42-600');
INSERT INTO PlaneType(Name) VALUES ('Aerospatiale/Alenia ATR 72');
INSERT INTO PlaneType(Name) VALUES ('Airbus A300');
INSERT INTO PlaneType(Name) VALUES ('Airbus A300-600');
INSERT INTO PlaneType(Name) VALUES ('Airbus A300-600ST Super Transporter / Beluga');
INSERT INTO PlaneType(Name) VALUES ('Airbus A310');
INSERT INTO PlaneType(Name) VALUES ('Airbus A318');
INSERT INTO PlaneType(Name) VALUES ('Airbus A319');
INSERT INTO PlaneType(Name) VALUES ('Airbus A319neo');
INSERT INTO PlaneType(Name) VALUES ('Airbus A320');
INSERT INTO PlaneType(Name) VALUES ('Airbus A320neo');
INSERT INTO PlaneType(Name) VALUES ('Airbus A321');
INSERT INTO PlaneType(Name) VALUES ('Airbus A321neo');
INSERT INTO PlaneType(Name) VALUES ('Airbus A330');
INSERT INTO PlaneType(Name) VALUES ('Airbus A330-200');
INSERT INTO PlaneType(Name) VALUES ('Airbus A330-300');
INSERT INTO PlaneType(Name) VALUES ('Airbus A330-700 Beluga XL');
INSERT INTO PlaneType(Name) VALUES ('Airbus A330-800neo');
INSERT INTO PlaneType(Name) VALUES ('Airbus A330-900neo');
INSERT INTO PlaneType(Name) VALUES ('Airbus A340');
INSERT INTO PlaneType(Name) VALUES ('Airbus A340-200');
INSERT INTO PlaneType(Name) VALUES ('Airbus A340-300');
INSERT INTO PlaneType(Name) VALUES ('Airbus A340-500');
INSERT INTO PlaneType(Name) VALUES ('Airbus A340-600');
INSERT INTO PlaneType(Name) VALUES ('Airbus A350');
INSERT INTO PlaneType(Name) VALUES ('Airbus A350-1000');
INSERT INTO PlaneType(Name) VALUES ('Airbus A350-900');
INSERT INTO PlaneType(Name) VALUES ('Airbus A380');
INSERT INTO PlaneType(Name) VALUES ('Airbus A380-800');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-12');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-124 Ruslan');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-140');
INSERT INTO PlaneType(Name) VALUES ('Antonov An-148');
INSERT INTO PlaneType(Name) VALUES ('Antonov An-158');
INSERT INTO PlaneType(Name) VALUES ('Antonov An-225 Mriya');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-24');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-26');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-28');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-30');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-32');
INSERT INTO PlaneType(Name) VALUES ('Antonov AN-72');
INSERT INTO PlaneType(Name) VALUES ('Avro RJ100');
INSERT INTO PlaneType(Name) VALUES ('Avro RJ70');
INSERT INTO PlaneType(Name) VALUES ('Avro RJ85');
INSERT INTO PlaneType(Name) VALUES ('BAe 146');
INSERT INTO PlaneType(Name) VALUES ('BAe 146-100');
INSERT INTO PlaneType(Name) VALUES ('BAe 146-200');
INSERT INTO PlaneType(Name) VALUES ('BAe 146-300');
INSERT INTO PlaneType(Name) VALUES ('Beechcraft 1900');
INSERT INTO PlaneType(Name) VALUES ('Beechcraft Baron');
INSERT INTO PlaneType(Name) VALUES ('Beechcraft Baron / 55 Baron');
INSERT INTO PlaneType(Name) VALUES ('Bell 212');
INSERT INTO PlaneType(Name) VALUES ('Boeing 707');
INSERT INTO PlaneType(Name) VALUES ('Boeing 717');
INSERT INTO PlaneType(Name) VALUES ('Boeing 720B');
INSERT INTO PlaneType(Name) VALUES ('Boeing 727');
INSERT INTO PlaneType(Name) VALUES ('Boeing 727-100');
INSERT INTO PlaneType(Name) VALUES ('Boeing 727-200');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737 MAX 10');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737 MAX 7');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737 MAX 8');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737 MAX 9');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-200');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-300');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-400');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-500');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-600');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-700');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-800');
INSERT INTO PlaneType(Name) VALUES ('Boeing 737-900');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747 LCF Dreamlifter');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747-100');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747-200');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747-300');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747-400');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747-400D');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747-8');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747SP');
INSERT INTO PlaneType(Name) VALUES ('Boeing 747SR');
INSERT INTO PlaneType(Name) VALUES ('Boeing 757');
INSERT INTO PlaneType(Name) VALUES ('Boeing 757-200');
INSERT INTO PlaneType(Name) VALUES ('Boeing 757-300');
INSERT INTO PlaneType(Name) VALUES ('Boeing 767');
INSERT INTO PlaneType(Name) VALUES ('Boeing 767-200');
INSERT INTO PlaneType(Name) VALUES ('Boeing 767-300');
INSERT INTO PlaneType(Name) VALUES ('Boeing 767-400');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777-200');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777-200LR');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777-300');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777-300ER');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777-8');
INSERT INTO PlaneType(Name) VALUES ('Boeing 777-9');
INSERT INTO PlaneType(Name) VALUES ('Boeing 787');
INSERT INTO PlaneType(Name) VALUES ('Boeing 787-10');
INSERT INTO PlaneType(Name) VALUES ('Boeing 787-8');
INSERT INTO PlaneType(Name) VALUES ('Boeing 787-9');
INSERT INTO PlaneType(Name) VALUES ('Bombardier 415');
INSERT INTO PlaneType(Name) VALUES ('Bombardier BD-100 Challenger 300');
INSERT INTO PlaneType(Name) VALUES ('Bombardier CS100');
INSERT INTO PlaneType(Name) VALUES ('Bombardier CS300');
INSERT INTO PlaneType(Name) VALUES ('Bombardier Global Express');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace (BAC) One Eleven');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace 125 series / Hawker/Raytheon 700/800/800XP/850/900');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace 125-1000 series / Hawker/Raytheon 1000');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace ATP');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace Jetstream 31');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace Jetstream 32');
INSERT INTO PlaneType(Name) VALUES ('British Aerospace Jetstream 41');
INSERT INTO PlaneType(Name) VALUES ('Canadair Challenger');
INSERT INTO PlaneType(Name) VALUES ('Canadair CL-44');
INSERT INTO PlaneType(Name) VALUES ('Canadair Regional Jet 100');
INSERT INTO PlaneType(Name) VALUES ('Canadair Regional Jet 1000');
INSERT INTO PlaneType(Name) VALUES ('Canadair Regional Jet 200');
INSERT INTO PlaneType(Name) VALUES ('Canadair Regional Jet 700');
INSERT INTO PlaneType(Name) VALUES ('Canadair Regional Jet 900');
INSERT INTO PlaneType(Name) VALUES ('Cessna 152');
INSERT INTO PlaneType(Name) VALUES ('Cessna 172');
INSERT INTO PlaneType(Name) VALUES ('Cessna 182 Skylane');
INSERT INTO PlaneType(Name) VALUES ('Cessna 208 Caravan');
INSERT INTO PlaneType(Name) VALUES ('Cessna 210 Centurion');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation CJ3');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation CJ4');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation Excel');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation I');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation II');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation Mustang');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation Sovereign');
INSERT INTO PlaneType(Name) VALUES ('Cessna Citation X');
INSERT INTO PlaneType(Name) VALUES ('COMAC C-919');
INSERT INTO PlaneType(Name) VALUES ('Concorde');
INSERT INTO PlaneType(Name) VALUES ('Dassault Falcon 2000');
INSERT INTO PlaneType(Name) VALUES ('Dassault Falcon 50');
INSERT INTO PlaneType(Name) VALUES ('Dassault Falcon 7X');
INSERT INTO PlaneType(Name) VALUES ('Dassault Falcon 900');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-2 Beaver');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-2 Turbo-Beaver');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-3 Otter');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-4 Caribou');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-6 Twin Otter');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-7 Dash 7');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-8-100 Dash 8 / 8Q');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-8-200 Dash 8 / 8Q');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-8-300 Dash 8');
INSERT INTO PlaneType(Name) VALUES ('De Havilland Canada DHC-8-400 Dash 8Q');
INSERT INTO PlaneType(Name) VALUES ('De Havilland DH.104 Dove');
INSERT INTO PlaneType(Name) VALUES ('De Havilland DH.114 Heron');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-10');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-3');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-6');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-8-50');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-8-62');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-8-72');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-9-10');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-9-20');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-9-30');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-9-40');
INSERT INTO PlaneType(Name) VALUES ('Douglas DC-9-50');
INSERT INTO PlaneType(Name) VALUES ('Embraer 170');
INSERT INTO PlaneType(Name) VALUES ('Embraer 175');
INSERT INTO PlaneType(Name) VALUES ('Embraer 175 (long wing)');
INSERT INTO PlaneType(Name) VALUES ('Embraer 175 (short wing)');
INSERT INTO PlaneType(Name) VALUES ('Embraer 190');
INSERT INTO PlaneType(Name) VALUES ('Embraer 195');
INSERT INTO PlaneType(Name) VALUES ('Embraer E190-E2');
INSERT INTO PlaneType(Name) VALUES ('Embraer E195-E2');
INSERT INTO PlaneType(Name) VALUES ('Embraer EMB 110 Bandeirante');
INSERT INTO PlaneType(Name) VALUES ('Embraer EMB 120 Brasilia');
INSERT INTO PlaneType(Name) VALUES ('Embraer Legacy 450');
INSERT INTO PlaneType(Name) VALUES ('Embraer Legacy 600');
INSERT INTO PlaneType(Name) VALUES ('Embraer Phenom 100');
INSERT INTO PlaneType(Name) VALUES ('Embraer Phenom 300');
INSERT INTO PlaneType(Name) VALUES ('Embraer RJ135');
INSERT INTO PlaneType(Name) VALUES ('Embraer RJ140');
INSERT INTO PlaneType(Name) VALUES ('Embraer RJ145');
INSERT INTO PlaneType(Name) VALUES ('Fairchild Dornier 328JET');
INSERT INTO PlaneType(Name) VALUES ('Fairchild Dornier Do.228');
INSERT INTO PlaneType(Name) VALUES ('Fairchild Dornier Do.328');
INSERT INTO PlaneType(Name) VALUES ('Fokker 100');
INSERT INTO PlaneType(Name) VALUES ('Fokker 50');
INSERT INTO PlaneType(Name) VALUES ('Fokker 70');
INSERT INTO PlaneType(Name) VALUES ('Fokker F27 Friendship');
INSERT INTO PlaneType(Name) VALUES ('Fokker F28 Fellowship');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream Aerospace G-159 Gulfstream I');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream G280');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream G650');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream IV');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream V');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream/Rockwell (Aero) Commander');
INSERT INTO PlaneType(Name) VALUES ('Gulfstream/Rockwell (Aero) Turbo Commander');
INSERT INTO PlaneType(Name) VALUES ('Harbin Yunshuji Y12');
INSERT INTO PlaneType(Name) VALUES ('Hawker Siddeley HS 748');
INSERT INTO PlaneType(Name) VALUES ('Ilyushin IL114');
INSERT INTO PlaneType(Name) VALUES ('Ilyushin IL18');
INSERT INTO PlaneType(Name) VALUES ('Ilyushin IL62');
INSERT INTO PlaneType(Name) VALUES ('Ilyushin IL76');
INSERT INTO PlaneType(Name) VALUES ('Ilyushin IL86');
INSERT INTO PlaneType(Name) VALUES ('Ilyushin IL96');
INSERT INTO PlaneType(Name) VALUES ('Learjet 35');
INSERT INTO PlaneType(Name) VALUES ('Learjet 60');
INSERT INTO PlaneType(Name) VALUES ('Lockheed L-1011 Tristar');
INSERT INTO PlaneType(Name) VALUES ('Lockheed L-1049 Super Constellation');
INSERT INTO PlaneType(Name) VALUES ('Lockheed L-182 / 282 / 382 (L-100) Hercules');
INSERT INTO PlaneType(Name) VALUES ('Lockheed L-188 Electra');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-11');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-81');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-82');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-83');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-87');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-88');
INSERT INTO PlaneType(Name) VALUES ('McDonnell Douglas MD-90');
INSERT INTO PlaneType(Name) VALUES ('NAMC YS-11');
INSERT INTO PlaneType(Name) VALUES ('Partenavia P.68');
INSERT INTO PlaneType(Name) VALUES ('Pilatus Britten-Norman BN-2A Mk III Trislander');
INSERT INTO PlaneType(Name) VALUES ('Pilatus Britten-Norman BN-2A/B Islander');
INSERT INTO PlaneType(Name) VALUES ('Pilatus PC-12');
INSERT INTO PlaneType(Name) VALUES ('Pilatus PC-6 Turbo Porter');
INSERT INTO PlaneType(Name) VALUES ('Piper PA-28 (above 200hp)');
INSERT INTO PlaneType(Name) VALUES ('Piper PA-28 (up to 180hp)');
INSERT INTO PlaneType(Name) VALUES ('Piper PA-31 Navajo');
INSERT INTO PlaneType(Name) VALUES ('Piper PA-44 Seminole');
INSERT INTO PlaneType(Name) VALUES ('Piper PA-46');
INSERT INTO PlaneType(Name) VALUES ('Saab 2000');
INSERT INTO PlaneType(Name) VALUES ('Saab SF340A/B');
INSERT INTO PlaneType(Name) VALUES ('Shorts SC-5 Belfast');
INSERT INTO PlaneType(Name) VALUES ('Shorts SC-7 Skyvan');
INSERT INTO PlaneType(Name) VALUES ('Shorts SD.330');
INSERT INTO PlaneType(Name) VALUES ('Shorts SD.360');
INSERT INTO PlaneType(Name) VALUES ('Sikorsky S-58T');
INSERT INTO PlaneType(Name) VALUES ('Sikorsky S-61');
INSERT INTO PlaneType(Name) VALUES ('Sikorsky S-76');
INSERT INTO PlaneType(Name) VALUES ('Sikorsky S-92');
INSERT INTO PlaneType(Name) VALUES ('Sukhoi Superjet 100-95');
INSERT INTO PlaneType(Name) VALUES ('Tupolev Tu-134');
INSERT INTO PlaneType(Name) VALUES ('Tupolev Tu-144');
INSERT INTO PlaneType(Name) VALUES ('Tupolev Tu-154');
INSERT INTO PlaneType(Name) VALUES ('Tupolev Tu-204');
INSERT INTO PlaneType(Name) VALUES ('Yakovlev Yak-40');
INSERT INTO PlaneType(Name) VALUES ('Yakovlev Yak-42');
